// Field types: text, textarea, number, boolean, password
// Param types: path (substituted into URL), query, body

export const sections = [
  {
    name: "Auth",
    endpoints: [
      {
        id: "signup-google",
        label: "POST /signup",
        method: "POST",
        path: "/signup",
        description: "Sign up with Google OAuth token.",
        fields: [
          { name: "token", label: "Google Token", type: "textarea", paramType: "body", bodyKey: "googleResponse.token" },
          { name: "groupSlug", label: "Group Slug (optional)", type: "text", paramType: "body" },
        ],
      },
      {
        id: "signup-email",
        label: "POST /signup/email",
        method: "POST",
        path: "/signup/email",
        description: "Sign up with email and password.",
        fields: [
          { name: "firstName", label: "First Name", type: "text", paramType: "body" },
          { name: "lastName", label: "Last Name", type: "text", paramType: "body" },
          { name: "email", label: "Email", type: "text", paramType: "body" },
          { name: "password", label: "Password", type: "password", paramType: "body" },
          { name: "groupSlug", label: "Group Slug (optional)", type: "text", paramType: "body" },
        ],
      },
      {
        id: "login-google",
        label: "POST /login",
        method: "POST",
        path: "/login",
        description: "Log in with Google OAuth token.",
        fields: [
          { name: "token", label: "Google Token", type: "textarea", paramType: "body", bodyKey: "googleResponse.token" },
        ],
      },
      {
        id: "login-email",
        label: "POST /login/email",
        method: "POST",
        path: "/login/email",
        description: "Log in with email and password.",
        fields: [
          { name: "email", label: "Email", type: "text", paramType: "body" },
          { name: "password", label: "Password", type: "password", paramType: "body" },
        ],
      },
      {
        id: "reset-password",
        label: "POST /reset-password",
        method: "POST",
        path: "/reset-password",
        description: "Reset password using a token.",
        fields: [
          { name: "token", label: "Reset Token", type: "text", paramType: "body" },
          { name: "password", label: "New Password", type: "password", paramType: "body" },
        ],
      },
      {
        id: "reset-password-verify",
        label: "GET /reset-password/verify",
        method: "GET",
        path: "/reset-password/verify",
        description: "Verify a password reset token.",
        fields: [
          { name: "token", label: "Token", type: "text", paramType: "query" },
        ],
      },
    ],
  },
  {
    name: "Users",
    endpoints: [
      {
        id: "get-user",
        label: "GET /user",
        method: "GET",
        path: "/user",
        description: "Get the authenticated user's profile. Auth required.",
        auth: true,
        fields: [],
      },
      {
        id: "get-user-by-link",
        label: "GET /users/:userLink",
        method: "GET",
        path: "/users/:userLink",
        description: "Get a user's public profile by username.",
        fields: [
          { name: "userLink", label: "Username (userLink)", type: "text", paramType: "path" },
        ],
      },
      {
        id: "get-all-users",
        label: "GET /users/all",
        method: "GET",
        path: "/users/all",
        description: "Get all users.",
        fields: [],
      },
      {
        id: "update-profile",
        label: "PUT /user/profile",
        method: "PUT",
        path: "/user/profile",
        description: "Update the authenticated user's profile. Auth required.",
        auth: true,
        fields: [
          { name: "firstName", label: "First Name", type: "text", paramType: "body" },
          { name: "lastName", label: "Last Name", type: "text", paramType: "body" },
          { name: "userLink", label: "Username (userLink)", type: "text", paramType: "body" },
        ],
      },
      {
        id: "update-websites",
        label: "PUT /user/websites",
        method: "PUT",
        path: "/user/websites",
        description: "Update the authenticated user's linked websites. Auth required.",
        auth: true,
        fields: [
          { name: "twitter", label: "Twitter Handle", type: "text", paramType: "body" },
          { name: "website", label: "Website URL", type: "text", paramType: "body" },
        ],
      },
    ],
  },
  {
    name: "Social / Following",
    endpoints: [
      {
        id: "get-followers",
        label: "GET /user/followers",
        method: "GET",
        path: "/user/followers",
        description: "Get users who follow the authenticated user. Auth required.",
        auth: true,
        fields: [],
      },
      {
        id: "get-following",
        label: "GET /user/following",
        method: "GET",
        path: "/user/following",
        description: "Get users the authenticated user follows. Auth required.",
        auth: true,
        fields: [],
      },
      {
        id: "follow-user",
        label: "POST /user/following",
        method: "POST",
        path: "/user/following",
        description: "Follow a user. Auth required.",
        auth: true,
        fields: [
          { name: "toUid", label: "User ID to Follow", type: "number", paramType: "body" },
        ],
      },
      {
        id: "unfollow-user",
        label: "DELETE /user/following/:toUid",
        method: "DELETE",
        path: "/user/following/:toUid",
        description: "Unfollow a user. Auth required.",
        auth: true,
        fields: [
          { name: "toUid", label: "User ID to Unfollow", type: "number", paramType: "path" },
        ],
      },
      {
        id: "following-links",
        label: "GET /users/:uid/followingLinks",
        method: "GET",
        path: "/users/:uid/followingLinks",
        description: "Get the most recent link from each person a user follows.",
        fields: [
          { name: "uid", label: "User ID", type: "number", paramType: "path" },
        ],
      },
      {
        id: "following-reads",
        label: "GET /users/:uid/followingReads",
        method: "GET",
        path: "/users/:uid/followingReads",
        description: "Get the most recent read from each followed user.",
        fields: [
          { name: "uid", label: "User ID", type: "number", paramType: "path" },
        ],
      },
      {
        id: "following-highlights",
        label: "GET /users/:uid/followingHighlights",
        method: "GET",
        path: "/users/:uid/followingHighlights",
        description: "Get the most recent highlight from each followed user.",
        fields: [
          { name: "uid", label: "User ID", type: "number", paramType: "path" },
        ],
      },
      {
        id: "suggested-follows",
        label: "GET /users/:uid/suggestedFollows",
        method: "GET",
        path: "/users/:uid/suggestedFollows",
        description: "Get suggested users to follow, ranked by mutual connections.",
        fields: [
          { name: "uid", label: "User ID", type: "number", paramType: "path" },
        ],
      },
      {
        id: "recommended-users",
        label: "GET /recommendedUsers",
        method: "GET",
        path: "/recommendedUsers",
        description: "Get recommended users (within 2 degrees, active in last 30 days). Auth required.",
        auth: true,
        fields: [],
      },
    ],
  },
  {
    name: "Links",
    endpoints: [
      {
        id: "get-user-links",
        label: "GET /users/:uid/links",
        method: "GET",
        path: "/users/:uid/links",
        description: "Get a user's bookmarks.",
        fields: [
          { name: "uid", label: "User ID", type: "number", paramType: "path" },
          { name: "page", label: "Page", type: "number", paramType: "query" },
          { name: "query", label: "Search Query", type: "text", paramType: "query" },
          { name: "favorited", label: "Favorited (0/1)", type: "number", paramType: "query" },
          { name: "toRead", label: "To Read (0/1)", type: "number", paramType: "query" },
          { name: "topicSlug", label: "Topic Slug", type: "text", paramType: "query" },
          { name: "trailHash", label: "Trail Hash", type: "text", paramType: "query" },
        ],
      },
      {
        id: "get-links",
        label: "GET /links",
        method: "GET",
        path: "/links",
        description: "Get links with filtering.",
        fields: [
          { name: "page", label: "Page", type: "number", paramType: "query" },
          { name: "query", label: "Search Query", type: "text", paramType: "query" },
          { name: "favorited", label: "Favorited (0/1)", type: "number", paramType: "query" },
          { name: "toRead", label: "To Read (0/1)", type: "number", paramType: "query" },
          { name: "topicSlug", label: "Topic Slug", type: "text", paramType: "query" },
          { name: "trailHash", label: "Trail Hash", type: "text", paramType: "query" },
        ],
      },
      {
        id: "get-all-links",
        label: "GET /links/all",
        method: "GET",
        path: "/links/all",
        description: "Get all links across the network, paginated.",
        fields: [
          { name: "page", label: "Page", type: "number", paramType: "query" },
          { name: "topicSlug", label: "Topic Slug", type: "text", paramType: "query" },
        ],
      },
      {
        id: "get-linkview",
        label: "GET /linkview/:id",
        method: "GET",
        path: "/linkview/:id",
        description: "Get a single link's detail view.",
        fields: [
          { name: "id", label: "Link ID", type: "number", paramType: "path" },
        ],
      },
      {
        id: "get-link-by-user",
        label: "GET /links/:id/user/:userLink",
        method: "GET",
        path: "/links/:id/user/:userLink",
        description: "Get a specific link saved by a specific user.",
        fields: [
          { name: "id", label: "Link ID", type: "number", paramType: "path" },
          { name: "userLink", label: "Username", type: "text", paramType: "path" },
        ],
      },
      {
        id: "save-new-link",
        label: "POST /links",
        method: "POST",
        path: "/links",
        description: "Save a new link. Auth required.",
        auth: true,
        fields: [
          { name: "title", label: "Title", type: "text", paramType: "body", bodyKey: "link.title" },
          { name: "link", label: "URL", type: "text", paramType: "body", bodyKey: "link.link" },
          { name: "snippet", label: "Snippet", type: "textarea", paramType: "body", bodyKey: "link.snippet" },
        ],
      },
      {
        id: "save-existing-link",
        label: "POST /links/:id",
        method: "POST",
        path: "/links/:id",
        description: "Save an existing link to bookshelf. Auth required.",
        auth: true,
        fields: [
          { name: "id", label: "Link ID", type: "number", paramType: "path" },
          { name: "toRead", label: "To Read", type: "boolean", paramType: "body" },
        ],
      },
      {
        id: "get-link-by-id",
        label: "GET /links/:id",
        method: "GET",
        path: "/links/:id",
        description: "Get a link by ID. Auth required.",
        auth: true,
        fields: [
          { name: "id", label: "Link ID", type: "number", paramType: "path" },
        ],
      },
      {
        id: "delete-link",
        label: "DELETE /links/:id",
        method: "DELETE",
        path: "/links/:id",
        description: "Delete a link from bookshelf. Auth required.",
        auth: true,
        fields: [
          { name: "id", label: "Link ID", type: "number", paramType: "path" },
        ],
      },
      {
        id: "rename-link",
        label: "POST /links/:id/title",
        method: "POST",
        path: "/links/:id/title",
        description: "Rename a link. Auth required.",
        auth: true,
        fields: [
          { name: "id", label: "Link ID", type: "number", paramType: "path" },
          { name: "title", label: "New Title", type: "text", paramType: "body" },
        ],
      },
      {
        id: "favorite-link",
        label: "POST /links/:id/favorite",
        method: "POST",
        path: "/links/:id/favorite",
        description: "Set favorite status on a link. Auth required.",
        auth: true,
        fields: [
          { name: "id", label: "Link ID", type: "number", paramType: "path" },
          { name: "favorite", label: "Favorite", type: "boolean", paramType: "body" },
        ],
      },
      {
        id: "rate-link",
        label: "POST /links/:id/rating",
        method: "POST",
        path: "/links/:id/rating",
        description: "Rate a link (0–5). Auth required.",
        auth: true,
        fields: [
          { name: "id", label: "Link ID", type: "number", paramType: "path" },
          { name: "rating", label: "Rating (0–5)", type: "number", paramType: "body" },
        ],
      },
      {
        id: "classify-link",
        label: "POST /links/:id/classify",
        method: "POST",
        path: "/links/:id/classify",
        description: "Auto-classify a link's topic using ML. Auth required.",
        auth: true,
        fields: [
          { name: "id", label: "Link ID", type: "number", paramType: "path" },
          { name: "doc", label: "Document Text", type: "textarea", paramType: "body" },
        ],
      },
      {
        id: "related-links",
        label: "GET /links/:id/related",
        method: "GET",
        path: "/links/:id/related",
        description: "Get related links.",
        fields: [
          { name: "id", label: "Link ID", type: "number", paramType: "path" },
        ],
      },
      {
        id: "lookup-link-url",
        label: "POST /links/url",
        method: "POST",
        path: "/links/url",
        description: "Look up a link by URL. Auth required.",
        auth: true,
        fields: [
          { name: "url", label: "URL", type: "text", paramType: "body" },
        ],
      },
      {
        id: "lookup-link-url-network",
        label: "POST /links/url/network",
        method: "POST",
        path: "/links/url/network",
        description: "Look up a link by URL with network interactions. Auth required.",
        auth: true,
        fields: [
          { name: "url", label: "URL", type: "text", paramType: "body" },
        ],
      },
      {
        id: "get-favorites",
        label: "GET /favorites",
        method: "GET",
        path: "/favorites",
        description: "Get the network's favorite links. Auth required.",
        auth: true,
        fields: [],
      },
    ],
  },
  {
    name: "Highlights",
    endpoints: [
      {
        id: "get-highlights",
        label: "GET /links/:id/highlights",
        method: "GET",
        path: "/links/:id/highlights",
        description: "Get highlights for a link. Auth required.",
        auth: true,
        fields: [
          { name: "id", label: "Link ID", type: "number", paramType: "path" },
        ],
      },
      {
        id: "add-highlight",
        label: "POST /links/:id/highlights",
        method: "POST",
        path: "/links/:id/highlights",
        description: "Add a highlight to a link. Auth required.",
        auth: true,
        fields: [
          { name: "id", label: "Link ID", type: "number", paramType: "path" },
          { name: "highlightText", label: "Highlight Text", type: "textarea", paramType: "body", bodyKey: "highlight.highlightText" },
          { name: "leftContext", label: "Left Context", type: "text", paramType: "body", bodyKey: "highlight.leftContext" },
          { name: "rightContext", label: "Right Context", type: "text", paramType: "body", bodyKey: "highlight.rightContext" },
          { name: "rawHighlight", label: "Raw Highlight", type: "text", paramType: "body", bodyKey: "highlight.rawHighlight" },
          { name: "position", label: "Position", type: "number", paramType: "body", bodyKey: "highlight.position" },
        ],
      },
      {
        id: "delete-highlight",
        label: "DELETE /links/:id/highlights",
        method: "DELETE",
        path: "/links/:id/highlights",
        description: "Delete a highlight. Auth required.",
        auth: true,
        fields: [
          { name: "id", label: "Link ID", type: "number", paramType: "path" },
          { name: "highlightText", label: "Highlight Text", type: "text", paramType: "body" },
        ],
      },
      {
        id: "get-snippets",
        label: "GET /snippets",
        method: "GET",
        path: "/snippets",
        description: "Get recent highlights across the network.",
        fields: [
          { name: "page", label: "Page", type: "number", paramType: "query" },
          { name: "topicSlug", label: "Topic Slug", type: "text", paramType: "query" },
          { name: "uid", label: "User ID", type: "number", paramType: "query" },
        ],
      },
      {
        id: "verify-highlight",
        label: "PUT /highlight/:id/verify",
        method: "PUT",
        path: "/highlight/:id/verify",
        description: "Verify a highlight (admin only). Auth required.",
        auth: true,
        fields: [
          { name: "id", label: "Highlight ID", type: "number", paramType: "path" },
          { name: "verify", label: "Verify", type: "boolean", paramType: "body" },
        ],
      },
      {
        id: "random-highlight",
        label: "POST /links/randomHighlight",
        method: "POST",
        path: "/links/randomHighlight",
        description: "Get a random highlight from a user.",
        fields: [
          { name: "uid", label: "User ID", type: "number", paramType: "body" },
        ],
      },
    ],
  },
  {
    name: "Comments & Mentions",
    endpoints: [
      {
        id: "add-comment",
        label: "POST /links/:id/comment",
        method: "POST",
        path: "/links/:id/comment",
        description: "Add a comment on a link. Auth required.",
        auth: true,
        fields: [
          { name: "id", label: "Link ID", type: "number", paramType: "path" },
          { name: "commentText", label: "Comment Text", type: "textarea", paramType: "body" },
          { name: "trailHash", label: "Trail Hash (optional)", type: "text", paramType: "query" },
        ],
      },
      {
        id: "upsert-comment",
        label: "PUT /links/:id/comment",
        method: "PUT",
        path: "/links/:id/comment",
        description: "Upsert a comment on a link. Auth required.",
        auth: true,
        fields: [
          { name: "id", label: "Link ID", type: "number", paramType: "path" },
          { name: "commentText", label: "Comment Text", type: "textarea", paramType: "body" },
        ],
      },
      {
        id: "upsert-highlight-comment",
        label: "PUT /links/:id/highlight/comment",
        method: "PUT",
        path: "/links/:id/highlight/comment",
        description: "Upsert a comment on a highlight. Auth required.",
        auth: true,
        fields: [
          { name: "id", label: "Link ID", type: "number", paramType: "path" },
          { name: "commentText", label: "Comment Text", type: "textarea", paramType: "body" },
          { name: "highlightId", label: "Highlight ID", type: "number", paramType: "body" },
        ],
      },
      {
        id: "reply-comment",
        label: "POST /comments",
        method: "POST",
        path: "/comments",
        description: "Reply to a comment. Auth required.",
        auth: true,
        fields: [
          { name: "commentId", label: "Parent Comment ID", type: "number", paramType: "body" },
          { name: "replyText", label: "Reply Text", type: "textarea", paramType: "body" },
        ],
      },
      {
        id: "edit-comment",
        label: "PUT /comments",
        method: "PUT",
        path: "/comments",
        description: "Edit a comment. Auth required.",
        auth: true,
        fields: [
          { name: "commentId", label: "Comment ID", type: "number", paramType: "body" },
          { name: "commentText", label: "New Text", type: "textarea", paramType: "body" },
        ],
      },
      {
        id: "delete-comment",
        label: "DELETE /comments",
        method: "DELETE",
        path: "/comments",
        description: "Delete a comment. Auth required.",
        auth: true,
        fields: [
          { name: "commentId", label: "Comment ID", type: "number", paramType: "body" },
        ],
      },
      {
        id: "mention-user",
        label: "POST /links/:id/mention",
        method: "POST",
        path: "/links/:id/mention",
        description: "Mention a user on a link. Auth required.",
        auth: true,
        fields: [
          { name: "id", label: "Link ID", type: "number", paramType: "path" },
          { name: "toUid", label: "User ID to Mention", type: "number", paramType: "body" },
        ],
      },
      {
        id: "upsert-mentions",
        label: "PUT /links/:id/mention",
        method: "PUT",
        path: "/links/:id/mention",
        description: "Upsert mentions on a link. Auth required.",
        auth: true,
        fields: [
          { name: "id", label: "Link ID", type: "number", paramType: "path" },
          { name: "toUids", label: "User IDs (comma-separated)", type: "text", paramType: "body" },
        ],
      },
    ],
  },
  {
    name: "Topics",
    endpoints: [
      {
        id: "get-user-topics",
        label: "GET /user/topics",
        method: "GET",
        path: "/user/topics",
        description: "Get topics for a user.",
        fields: [
          { name: "uid", label: "User ID (optional)", type: "number", paramType: "query" },
        ],
      },
      {
        id: "get-popular-topics",
        label: "GET /topics",
        method: "GET",
        path: "/topics",
        description: "Get popular topic suggestions.",
        fields: [],
      },
      {
        id: "create-topic",
        label: "POST /user/topics",
        method: "POST",
        path: "/user/topics",
        description: "Create a new topic. Auth required.",
        auth: true,
        fields: [
          { name: "topic", label: "Topic Name", type: "text", paramType: "body", bodyKey: "topic.topic" },
        ],
      },
      {
        id: "delete-topic",
        label: "DELETE /user/topics",
        method: "DELETE",
        path: "/user/topics",
        description: "Delete a topic. Auth required.",
        auth: true,
        fields: [
          { name: "topic", label: "Topic Name", type: "text", paramType: "body", bodyKey: "topic.topic" },
        ],
      },
      {
        id: "rename-topic",
        label: "PUT /user/topic",
        method: "PUT",
        path: "/user/topic",
        description: "Rename a topic. Auth required.",
        auth: true,
        fields: [
          { name: "topicId", label: "Topic ID", type: "number", paramType: "body", bodyKey: "topic.id" },
          { name: "topicName", label: "New Name", type: "text", paramType: "body" },
        ],
      },
      {
        id: "get-link-topics",
        label: "GET /links/:id/topics",
        method: "GET",
        path: "/links/:id/topics",
        description: "Get topics for a link. Auth required.",
        auth: true,
        fields: [
          { name: "id", label: "Link ID", type: "number", paramType: "path" },
        ],
      },
      {
        id: "add-link-topic",
        label: "POST /links/:id/topics",
        method: "POST",
        path: "/links/:id/topics",
        description: "Add a topic to a link. Auth required.",
        auth: true,
        fields: [
          { name: "id", label: "Link ID", type: "number", paramType: "path" },
          { name: "topic", label: "Topic Name", type: "text", paramType: "body", bodyKey: "topic.topic" },
        ],
      },
      {
        id: "upsert-link-topics",
        label: "PUT /links/:id/topics",
        method: "PUT",
        path: "/links/:id/topics",
        description: "Replace all topics on a link. Auth required.",
        auth: true,
        fields: [
          { name: "id", label: "Link ID", type: "number", paramType: "path" },
          { name: "topics", label: "Topics (comma-separated)", type: "text", paramType: "body" },
        ],
      },
      {
        id: "delete-link-topic",
        label: "DELETE /links/:id/topics",
        method: "DELETE",
        path: "/links/:id/topics",
        description: "Remove a topic from a link. Auth required.",
        auth: true,
        fields: [
          { name: "id", label: "Link ID", type: "number", paramType: "path" },
          { name: "topic", label: "Topic Name", type: "text", paramType: "body", bodyKey: "topic.topic" },
        ],
      },
    ],
  },
  {
    name: "Trails",
    endpoints: [
      {
        id: "get-trails",
        label: "GET /trails/:uid",
        method: "GET",
        path: "/trails/:uid",
        description: "Get trails for a user.",
        fields: [
          { name: "uid", label: "User ID", type: "number", paramType: "path" },
        ],
      },
      {
        id: "get-trail-links",
        label: "GET /trails/:userLink/links",
        method: "GET",
        path: "/trails/:userLink/links",
        description: "Get trail links for a user.",
        fields: [
          { name: "userLink", label: "Username", type: "text", paramType: "path" },
        ],
      },
      {
        id: "get-trail-by-hash",
        label: "GET /gettrail/:hash",
        method: "GET",
        path: "/gettrail/:hash",
        description: "Get a trail by its hash.",
        fields: [
          { name: "hash", label: "Trail Hash", type: "text", paramType: "path" },
        ],
      },
      {
        id: "create-trail",
        label: "POST /trails",
        method: "POST",
        path: "/trails",
        description: "Create a trail. Auth required.",
        auth: true,
        fields: [
          { name: "name", label: "Trail Name", type: "text", paramType: "body" },
          { name: "uids", label: "Member User IDs (comma-separated)", type: "text", paramType: "body" },
        ],
      },
      {
        id: "edit-trail",
        label: "PUT /trails/edit",
        method: "PUT",
        path: "/trails/edit",
        description: "Edit a trail. Auth required.",
        auth: true,
        fields: [
          { name: "hash", label: "Trail Hash", type: "text", paramType: "body" },
          { name: "trailName", label: "Trail Name", type: "text", paramType: "body" },
          { name: "description", label: "Description", type: "textarea", paramType: "body" },
          { name: "colorHex", label: "Color Hex", type: "text", paramType: "body" },
          { name: "emojiUnicode", label: "Emoji Unicode", type: "text", paramType: "body" },
        ],
      },
      {
        id: "delete-trail",
        label: "PUT /trails/delete",
        method: "PUT",
        path: "/trails/delete",
        description: "Delete a trail. Auth required.",
        auth: true,
        fields: [
          { name: "hash", label: "Trail Hash", type: "text", paramType: "body" },
        ],
      },
      {
        id: "add-link-to-trail",
        label: "POST /links/:id/trails",
        method: "POST",
        path: "/links/:id/trails",
        description: "Add a link to a trail. Auth required.",
        auth: true,
        fields: [
          { name: "id", label: "Link ID", type: "number", paramType: "path" },
          { name: "trailHash", label: "Trail Hash", type: "text", paramType: "body" },
        ],
      },
      {
        id: "remove-link-from-trail",
        label: "DELETE /links/:id/trails",
        method: "DELETE",
        path: "/links/:id/trails",
        description: "Remove a link from a trail. Auth required.",
        auth: true,
        fields: [
          { name: "id", label: "Link ID", type: "number", paramType: "path" },
          { name: "trailHash", label: "Trail Hash", type: "text", paramType: "body" },
        ],
      },
    ],
  },
  {
    name: "Library & Groups",
    endpoints: [
      {
        id: "get-library",
        label: "GET /library",
        method: "GET",
        path: "/library",
        description: "Get the public library feed.",
        fields: [
          { name: "page", label: "Page", type: "number", paramType: "query" },
          { name: "groupSlug", label: "Group Slug", type: "text", paramType: "query" },
          { name: "explore", label: "Explore", type: "text", paramType: "query" },
          { name: "user", label: "User", type: "text", paramType: "query" },
        ],
      },
      {
        id: "get-library-topic",
        label: "GET /library/:topic",
        method: "GET",
        path: "/library/:topic",
        description: "Get links for a specific topic in the library.",
        fields: [
          { name: "topic", label: "Topic Slug", type: "text", paramType: "path" },
        ],
      },
      {
        id: "get-groups",
        label: "GET /groups",
        method: "GET",
        path: "/groups",
        description: "Get groups.",
        fields: [
          { name: "uid", label: "User ID (optional)", type: "number", paramType: "query" },
          { name: "groupSlug", label: "Group Slug (optional)", type: "text", paramType: "query" },
        ],
      },
      {
        id: "create-group",
        label: "POST /groups",
        method: "POST",
        path: "/groups",
        description: "Create a group. Auth required.",
        auth: true,
        fields: [
          { name: "name", label: "Group Name", type: "text", paramType: "body" },
          { name: "uids", label: "Member User IDs (comma-separated)", type: "text", paramType: "body" },
        ],
      },
      {
        id: "get-group-links",
        label: "GET /groupLinks",
        method: "GET",
        path: "/groupLinks",
        description: "Get links from group members.",
        fields: [
          { name: "groupSlug", label: "Group Slug", type: "text", paramType: "query" },
          { name: "user", label: "User", type: "text", paramType: "query" },
          { name: "overview", label: "Overview", type: "text", paramType: "query" },
        ],
      },
      {
        id: "add-user-to-group",
        label: "PUT /user/group",
        method: "PUT",
        path: "/user/group",
        description: "Add a user to a group. Auth required.",
        auth: true,
        fields: [
          { name: "uid", label: "User ID", type: "number", paramType: "body" },
          { name: "groupId", label: "Group ID", type: "number", paramType: "body" },
        ],
      },
      {
        id: "remove-user-from-group",
        label: "DELETE /user/group",
        method: "DELETE",
        path: "/user/group",
        description: "Remove a user from a group. Auth required.",
        auth: true,
        fields: [
          { name: "uid", label: "User ID", type: "number", paramType: "body" },
          { name: "groupId", label: "Group ID", type: "number", paramType: "body" },
        ],
      },
    ],
  },
  {
    name: "Search",
    endpoints: [
      {
        id: "search",
        label: "GET /search",
        method: "GET",
        path: "/search",
        description: "Search links by text or domain.",
        fields: [
          { name: "query", label: "Search Query", type: "text", paramType: "query" },
          { name: "domain", label: "Domain", type: "text", paramType: "query" },
        ],
      },
      {
        id: "user-search-links",
        label: "GET /users/:uid/searchLinks",
        method: "GET",
        path: "/users/:uid/searchLinks",
        description: "Get all of a user's links for client-side search.",
        fields: [
          { name: "uid", label: "User ID", type: "number", paramType: "path" },
        ],
      },
      {
        id: "passage-search",
        label: "GET /passageSearch",
        method: "GET",
        path: "/passageSearch",
        description: "Full-text passage search across all links.",
        fields: [
          { name: "query", label: "Search Query", type: "text", paramType: "query" },
        ],
      },
      {
        id: "passage-search-user",
        label: "GET /passageSearch/:uid",
        method: "GET",
        path: "/passageSearch/:uid",
        description: "Passage search scoped to a single user's links.",
        fields: [
          { name: "uid", label: "User ID", type: "number", paramType: "path" },
          { name: "query", label: "Search Query", type: "text", paramType: "query" },
        ],
      },
    ],
  },
  {
    name: "Activity & Notifications",
    endpoints: [
      {
        id: "get-activity",
        label: "GET /activity",
        method: "GET",
        path: "/activity",
        description: "Get notification feed. Auth required.",
        auth: true,
        fields: [],
      },
      {
        id: "mark-notifications-read",
        label: "PUT /user/notifications/update",
        method: "PUT",
        path: "/user/notifications/update",
        description: "Mark notifications as read. Auth required.",
        auth: true,
        fields: [],
      },
      {
        id: "links-activity",
        label: "GET /links/activity",
        method: "GET",
        path: "/links/activity",
        description: "Get global link activity.",
        fields: [],
      },
    ],
  },
  {
    name: "Misc",
    endpoints: [
      {
        id: "health",
        label: "GET /health",
        method: "GET",
        path: "/health",
        description: "Health check — returns service status.",
        fields: [],
      },
      {
        id: "get-stats",
        label: "GET /stats",
        method: "GET",
        path: "/stats",
        description: "Platform-wide stats (admin only). Auth required.",
        auth: true,
        fields: [],
      },
      {
        id: "wrapped-links",
        label: "GET /wrapped2022Links/:uid",
        method: "GET",
        path: "/wrapped2022Links/:uid",
        description: "Get a user's top links for 2022 wrapped.",
        fields: [
          { name: "uid", label: "User ID", type: "number", paramType: "path" },
        ],
      },
      {
        id: "wrapped-friends",
        label: "GET /wrapped2022Friends/:uid",
        method: "GET",
        path: "/wrapped2022Friends/:uid",
        description: "Get a user's friend activity for 2022 wrapped.",
        fields: [
          { name: "uid", label: "User ID", type: "number", paramType: "path" },
        ],
      },
    ],
  },
];

export const BASE_URL = "/api";
